// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "4f77d29e09aaeb54",
  "routes": [
    "",
    "editor/:presentationId",
    "feature",
    "present/:presentationId",
    "presenter/:presentationId"
  ],
  "services": [
    "PresentationStore"
  ],
  "components": [
    "AnonymousComponent@createPresentationPage",
    "App",
    "DashboardPage",
    "EditorPage"
  ],
  "primitives": [
    "activeCodeWorkspace",
    "activeDemoWorkspaceId",
    "activeLink",
    "addSection",
    "addSequence",
    "authoringMode",
    "autosaveStatus",
    "clearImage",
    "closeCodeWorkspace",
    "closeImageViewer",
    "closePresentationLink",
    "codeFileListVisible",
    "codeFileQuery",
    "codeFilesVisible",
    "codeQuickOpenVisible",
    "codeSearchQuery",
    "codeSearchVisible",
    "collapsedSectionIds",
    "coverImageAlt",
    "createPresentation",
    "createPresentationAndRevealLink",
    "createdPresentation",
    "currentDocument",
    "currentSectionIntention",
    "currentSectionTitle",
    "currentSlide",
    "deleteSequence",
    "demoWorkspaceConfigList",
    "demoWorkspaceConfigs",
    "demoWorkspaceProcessStatus",
    "exportContent",
    "exportFilename",
    "exportFormat",
    "handleImageFile",
    "handleKeydown",
    "hasActiveCodeWorkspace",
    "hasActiveLink",
    "hasBackgroundImage",
    "hasBackgroundMedia",
    "hasBackgroundVideo",
    "hasCode",
    "hasCoverImage",
    "hasCreatedPresentation",
    "hasDemoWorkspace",
    "hasDocument",
    "hasImage",
    "hasImageUploadNotice",
    "hasImageViewer",
    "hasMarkdownErrors",
    "highlightedCode",
    "highlightedWorkspaceCode",
    "imageUploadError",
    "imageUploadErrorMessage",
    "imageUploadFailed",
    "imageUploadNotice",
    "imageUploading",
    "imageViewer",
    "isAutosaving",
    "isImageBackground",
    "isMarkdownMode",
    "isMarkdownValid",
    "isMediaBackground",
    "isThemeBackground",
    "isVideoBackground",
    "isVisualMode",
    "linkReturnState",
    "markdownErrorMessage",
    "markdownErrors",
    "markdownSource",
    "markdownValue",
    "moveSection",
    "moveSequence",
    "newDemoWorkspaceCommand",
    "newDemoWorkspaceDirectory",
    "newDemoWorkspaceId",
    "newDemoWorkspacePort",
    "newDemoWorkspaceTitle",
    "newPresentationDraft",
    "next",
    "noWorkspaceFiles",
    "noteParts",
    "notesVisible",
    "openCodeWorkspace",
    "openDemoTerminal",
    "openImageViewer",
    "openPresentationLink",
    "overview",
    "presentationDemoWorkspace",
    "presentationDraft",
    "presentationEditor",
    "presentationStage",
    "presentations",
    "previous",
    "processIsBusy",
    "processIsRunning",
    "processStatus",
    "processStatusLabel",
    "processUrl",
    "progressPercent",
    "publicNotesHidden",
    "refreshDemoWorkspaceProcess",
    "runDemoCommand",
    "runDemoWorkspaceCommand",
    "saveChanges",
    "saveDemoWorkspaceConfig",
    "saveLocalDemoWorkspace",
    "savePresentation",
    "sectionNavigation",
    "sectionViews",
    "selectCodeFile",
    "selectSlide",
    "selectedCodePath",
    "selectedWorkspaceFile",
    "showOverviewContent",
    "showStage",
    "slideIndex",
    "slideItems",
    "slides",
    "startDemoWorkspaceProcess",
    "startMarkdownMode",
    "startVisualMode",
    "stopDemoWorkspaceProcess",
    "terminalCommand",
    "terminalIsBusy",
    "terminalVisible",
    "toggleCodeFiles",
    "toggleDemoTerminal",
    "toggleNotes",
    "toggleSection",
    "updateAudience",
    "updateBackgroundDecoration",
    "updateBackgroundDecorationColor",
    "updateBackgroundGradientAngle",
    "updateBackgroundGradientEnd",
    "updateBackgroundGradientMiddle",
    "updateBackgroundGradientStart",
    "updateBackgroundTheme",
    "updateBackgroundType",
    "updateBackgroundUrl",
    "updateCoverImageAlt",
    "updateDemoWorkspace",
    "updateLayout",
    "updateMarkdown",
    "updateObjective",
    "updateSection",
    "updateSequence",
    "updateTitle",
    "uploadPresentationImage",
    "visibleWorkspaceFiles",
    "workspaceFiles",
    "workspaceSearchMatches"
  ],
  "sources": [
    "draftChanges (signalSource)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "PresentationStore": [
        "src/server/presentation-store.ts",
        "src/server/presentation-store.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
