// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "580ed0e758c0879d",
  "routes": [
    "editor/:presentationId",
    "feature",
    "present/:presentationId",
    "presenter/:presentationId"
  ],
  "services": [
    "PresentationStore"
  ],
  "components": [
    "AnonymousComponent@155",
    "App",
    "DashboardPage",
    "EditorPage"
  ],
  "primitives": [
    "activeLink",
    "addSection",
    "addSequence",
    "autosaveStatus",
    "closePresentationLink",
    "collapsedSectionIds",
    "coverImageAlt",
    "createPresentation",
    "createPresentationAndRevealLink",
    "createdPresentation",
    "currentDocument",
    "currentSectionIntention",
    "currentSectionTitle",
    "currentSlide",
    "deleteSequence",
    "exportContent",
    "exportFilename",
    "exportFormat",
    "handleImageFile",
    "handleKeydown",
    "hasActiveLink",
    "hasCode",
    "hasCoverImage",
    "hasCreatedPresentation",
    "hasDocument",
    "hasImage",
    "hasImageUploadNotice",
    "highlightedCode",
    "imageUploadError",
    "imageUploadErrorMessage",
    "imageUploadFailed",
    "imageUploadNotice",
    "imageUploading",
    "isAutosaving",
    "linkReturnState",
    "moveSection",
    "newPresentationDraft",
    "next",
    "noteParts",
    "notesVisible",
    "openPresentationLink",
    "overview",
    "presentationDraft",
    "presentationEditor",
    "presentationStage",
    "presentations",
    "previous",
    "progressPercent",
    "publicNotesHidden",
    "saveChanges",
    "savePresentation",
    "sectionNavigation",
    "sectionViews",
    "selectSlide",
    "showOverviewContent",
    "showStage",
    "slideIndex",
    "slideItems",
    "slides",
    "toggleNotes",
    "toggleSection",
    "updateAudience",
    "updateCoverImageAlt",
    "updateLayout",
    "updateObjective",
    "updateSection",
    "updateSequence",
    "updateTitle",
    "uploadPresentationImage"
  ],
  "sources": [
    "draftChanges (signalSource)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "PresentationStore": [
        "src/server/presentation-store.ts",
        "src/server/presentation-store.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
